### ISSUE TITLE
ISO downloads are often timing out

### ISSUE THREAD

**Issue by alexjfisher** [petems/petems-rhel_mrepo_profiles#11]
Downloading a DVD iso image can take longer that 5 minutes even on a good connection.
What's the best way to extend the timeout?

https://github.com/puppetlabs/puppetlabs-mrepo/blob/master/manifests/iso.pp doesn't allow a timeout to be specified, so I guess the only way is through a resource default for `Staging::File`?

**Comment by petems** [comment]
Hmm, yeah that should probably have been exposed by the mrepo module itself, but I think the main usecase was downloading from local mirrors so it was a lot faster...

Exec timeout extension, or maybe I could just add a new ISO downloading defined type to this repo and we could reference that instead?

**Comment by alexjfisher** [comment]
I'm currently trying out https://github.com/alexjfisher/petems-rhel_mrepo_profiles/commit/8b0a4103d53c9bc96d29cdf5ffc6bab30d3dc95d

**Comment by petems** [comment]
@alexjfisher Did that work in the end/

**Comment by alexjfisher** [comment]
@petems Worked great.  I've opened https://github.com/petems/petems-rhel_mrepo_profiles/pull/18

**Comment by petems** [comment]
Closed via #19
